# Generated by Django 4.2.3 on 2023-09-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='describtion',
            new_name='description',
        ),
    ]
