# Generated by Django 4.2.3 on 2023-09-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='starts',
            new_name='stars',
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseFee',
            field=models.FloatField(),
        ),
    ]
