# Generated by Django 4.2.3 on 2023-09-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0005_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='candidatefd',
            new_name='candidateId',
        ),
    ]
