# Generated by Django 4.2.3 on 2023-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0006_rename_candidatefd_register_candidateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amountPaid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
