# Generated by Django 4.2.3 on 2023-09-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0008_alter_payments_amountpaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
